### ISSUE TITLE
Unable to understand pdf to xml convert code using pdf2xml

### ISSUE THREAD

**Issue by gitsnehasish** [WZBSocialScienceCenter/pdf2xml-viewer#1]
While running the below code in terminal. It is showing "'pdftohtml' is not recognized as an internal or external command,
operable program or batch file."

pdftohtml -c -hidden -xml input.pdf output.xml

Please help.

**Comment by internaut** [comment]
As mentioned in the README:

> At first, you need to convert your PDFs using the poppler-utils, a package which is part of most Linux distributions and is also available for OSX via Homebrew or MacPorts.

For Windows, I don't know how or if it is possible to install poppler-utils.
